name: "build binary"

on:
  push:
      branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build binary
        run: cargo build --release

      - uses: actions/upload-artifact@v2
        name: Upload binary
        with:
          name: menu-scraper
          path: target/release/menu-scraper
